kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: myingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web

spec:
  rules:
    - host: hello-world.traefik-yaml
      http:
        paths:
          - path: /
            backend:
              serviceName: tr-webapp
              servicePort: 8080
